ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: .github/|tests/testdata
      - id: end-of-file-fixer
        exclude: tests/testdata
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.7"
    hooks:
      - id: ruff-check
        args: ["--fix"]
  - repo: https://github.com/Pierre-Sassoulas/copyright_notice_precommit
    rev: 0.1.2
    hooks:
      - id: copyright-notice
        args: ["--notice=script/copyright.txt", "--enforce-all", "--autofix"]
        exclude: tests/testdata|setup.py
        types: [python]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        exclude: tests/testdata
        args: [--py310-plus]
  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker/
    rev: v1.1.3
    hooks:
      - id: black-disable-checker
        exclude: tests/test_nodes_lineno.py
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--safe, --quiet]
        exclude: tests/testdata
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn",
            "-sn",
            "--rcfile=pylintrc",
            # "--load-plugins=pylint.extensions.docparams", We're not ready for that
          ]
      # We define an additional manual step to allow running pylint
      # with the proper output for CI.
      - id: pylint
        alias: pylint-ci
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn",
            "-sn",
            "--rcfile=pylintrc",
            "--output-format=github",
            # "--load-plugins=pylint.extensions.docparams", We're not ready for that
          ]
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        language: python
        pass_filenames: false
        require_serial: true
        additional_dependencies: ["types-typed-ast"]
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt
