name: Release tests

on: workflow_dispatch

permissions:
  contents: read

jobs:
  virtualenv-15-windows-test:
    # Regression test added in https://github.com/PyCQA/astroid/pull/1386
    name: Regression test for virtualenv==15.1.0 on Windows
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.1.0
      - name: Set up Python 3.9
        id: python
        uses: actions/setup-python@v4.4.0
        with:
          # virtualenv 15.1.0 cannot be installed on Python 3.10+
          python-version: 3.9
      - name: Create Python virtual environment with virtualenv==15.1.0
        run: |
          python -m pip install virtualenv==15.1.0
          python -m virtualenv venv2
          . venv2\scripts\activate
          python -m pip install pylint
          python -m pip install -e .
      - name: Test no import-error from distutils.util
        run: |
          . venv2\scripts\activate
          echo "import distutils.util  # pylint: disable=unused-import" > test.py
          pylint test.py
